package net.micode.moneytracker.model

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Data model representing a financial account or wallet.
 * Each account can have its own set of transactions and budget settings.
 * 
 * @property id Unique identifier for the account, automatically generated by Room.
 * @property name The user-defined name of the account (e.g., "Cash", "Bank").
 * @property color The color integer used to represent this account in the UI.
 * @property isDefault True if this account is the primary account for the user.
 */
@Entity(tableName = "accounts")
data class Account(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val color: Int,
    val isDefault: Boolean = false
)
